[[models]]
name = "Hijiri"
scale = 1.5
enablebreathing = true
billboarding = false
[models.canvasOffset]
x = 0
[models.position]
x = 0
y = 0
z = 0.5
[models.rotation]
x = 0
y = 0
z = 0
[models.hitInfo]

[[models]]
name = "Otoha"
marker = "Hijiri"
scale = 1.5
enablebreathing = true
billboarding = false
[models.canvasOffset]
x = 0
[models.position]
x = 0
y = 0.8
z = -0.5
[models.rotation]
x = 0
y = 0
z = 0
[models.hitInfo]

[[models]]
name = "Ariura"
marker = "Hijiri"
scale = 1.5
enablebreathing = true
billboarding = false
[models.canvasOffset]
x = -0.5
[models.position]
x = 0
y = 0.5
z = 0
[models.rotation]
x = 0
y = 0
z = 0
[models.hitInfo]

[[models]]
name = "Clarice"
marker = "Hijiri"
scale = 1.5
enablebreathing = true
billboarding = false
[models.canvasOffset]
x = 0.5
[models.position]
x = 0
y = 0.5
z = 0
[models.rotation]
x = 0
y = 0
z = 0
[models.hitInfo]

[[global]]
allowModeSwitch = false
startupMode = 0
